spring:
  datasource:
    url: jdbc:mysql://121.41.53.32:3306/mall_pms?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.53.32:8848
    alicloud:
      access-key: LTAI4FzMfni1CGP8HB92jqUT
      secret-key: qba3N0ak47eofPzfRnHx9Az9dMk9vm
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 11000

logging:
  level:
    com.blackman.mall: debug