spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
      access-key: LTAI4FzMfni1CGP8HB92jqUT
      secret-key: qba3N0ak47eofPzfRnHx9Az9dMk9vm

server:
  port: 3000